-- Create a dedicated database for LiteLLM's Prisma-managed schema.
--
-- LiteLLM runs `prisma migrate deploy` on startup. The main `aigateway`
-- database is owned by the admin service's Alembic migrations, so pointing
-- Prisma at it fails with P3005 ("the database schema is not empty") on a
-- fresh deploy — Prisma refuses to migrate a non-empty schema it didn't
-- baseline. Giving LiteLLM its own empty database avoids the collision.
--
-- Runs only on first cluster initialisation (empty data dir), via the
-- postgres image's /docker-entrypoint-initdb.d/ hook, before the container
-- reports healthy — so the DB exists before LiteLLM (which waits for
-- postgres health) starts.
CREATE DATABASE litellm;
